# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


pod 'MessageKit'
pod 'JGProgressHUD'
pod 'RealmSwift'
pod 'SDWebImage'
pod 'SwiftLint'
pod 'SDWebImage'
#pod 'Firebase/Storage'
#pod 'Firebase/Auth'
#pod 'FirebaseCore'
#pod 'FirebaseDatabase'
#pod 'FirebaseFirestore'

end
